name: Node.js Test Workflow

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Success results
              run: echo "All tests passed"
              if: success()

            - name: Fail results
              run: echo "One or more tests failed"
              if: failure()
